import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
  head: () => ({ meta: [{ title: "Terms of Service — RealTalk" }] }),
});

function TermsPage() {
  const navigate = useNavigate();
  return (
    <div className="flex-1 max-w-3xl w-full mx-auto px-5 py-10">
      <button
        onClick={() => navigate({ to: "/profile", search: { tab: undefined } })}
        className="mb-6 flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
      >
        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" /></svg>
        Back
      </button>
      <h1 className="font-serif text-3xl tracking-tight">Terms of Service</h1>
      <p className="mt-3 text-sm text-muted-foreground">Last updated: April 19, 2026</p>

      <div className="mt-6 space-y-6 text-sm leading-relaxed text-foreground/90">

        <section>
          <h2 className="font-semibold text-base">Service scope</h2>
          <p className="mt-2 text-muted-foreground">
            RealTalk is an AI-powered companion for thinking, planning, venting, and personal clarity.
            It provides AI-assisted chat, plan generation, weekly insight summaries, and a personalised
            profile learning system. RealTalk is <strong>not</strong> a substitute for licensed medical,
            legal, financial, or psychological advice. In any emergency or crisis, contact your local
            emergency services immediately.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-base">Profile learning &amp; RealTime Neurons</h2>
          <p className="mt-2 text-muted-foreground">
            By using RealTalk, you consent to the automatic, background extraction of preference signals
            from your chat messages. This includes interests, communication style, life context, emotional
            tone, positive response signals, and comfort boundaries. These signals are used exclusively
            to personalise your RealTalk experience and to power the <strong>RealTime Neurons</strong>
            brain growth card on your profile.
          </p>
          <p className="mt-2 text-muted-foreground">
            Brain growth state is stored locally in your browser (localStorage) and is not backed up to
            our servers. This local state may be lost if you clear your browser data or use a different
            browser. The source profile data driving the neurons is always stored server-side.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-base">Weekly insights</h2>
          <p className="mt-2 text-muted-foreground">
            If you enable weekly insights, RealTalk will periodically generate a structured analysis of
            your emotional patterns, thought habits, and interaction quality. These summaries are stored
            in your account and can optionally be emailed to you. You may disable this feature at any
            time from your profile settings. Insight content is generated by AI and is reflective only
            — it is not a clinical assessment.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-base">AI providers &amp; service availability</h2>
          <p className="mt-2 text-muted-foreground">
            RealTalk uses Mistral AI as its primary AI provider, with automatic fallback to Google Gemini
            and Cloudflare Workers AI (Llama 3.1 8B) if the primary provider is unavailable. Response
            quality and availability may vary between providers. RealTalk makes no guarantee of
            uninterrupted service or consistent AI output. If an AI response fails, a retry option will
            be shown — you may use it to attempt the request again.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-base">Acceptable use</h2>
          <p className="mt-2 text-muted-foreground">
            You agree not to misuse RealTalk, attempt unauthorised access to the platform or other users'
            data, use the service for harmful, unlawful, or abusive activity, or attempt to extract,
            reverse-engineer, or abuse the AI systems. You must be at least 16 years old to use RealTalk.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-base">Gmail integration</h2>
          <p className="mt-2 text-muted-foreground">
            If you connect Google, you authorise RealTalk to send Gmail messages on your behalf only
            when you explicitly initiate a send action within the app. RealTalk does not read, store,
            or index your Gmail messages. Gmail connection is optional and can be disconnected at any time.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-base">Intellectual property</h2>
          <p className="mt-2 text-muted-foreground">
            All content, branding, and design of RealTalk — including the RealTime Neurons feature,
            logo, and UI — is the property of RealTalk LTD. You retain ownership of the content you
            submit (your chat messages, plans, etc.). By using the service, you grant RealTalk a limited
            licence to store and process your content solely to deliver the service.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-base">Limitation of liability</h2>
          <p className="mt-2 text-muted-foreground">
            RealTalk is provided "as is". We are not liable for decisions made based on AI-generated
            content, data loss resulting from browser storage being cleared, AI provider outages, or
            any indirect or consequential damages arising from use of the service.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-base">Changes to these terms</h2>
          <p className="mt-2 text-muted-foreground">
            We may update these terms as features evolve. Continued use of RealTalk after changes
            are posted constitutes acceptance of the updated terms. The "last updated" date above
            reflects the most recent revision.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-base">Data rights</h2>
          <p className="mt-2 text-muted-foreground">
            You can export your data (chats, plans, insights, profile preferences) and request
            permanent account deletion from the account data page.
          </p>
          <div className="mt-2">
            <Link to="/account-data" className="text-primary hover:underline">
              Go to account &amp; data export
            </Link>
          </div>
        </section>

        <section>
          <h2 className="font-semibold text-base">Contact</h2>
          <p className="mt-2 text-muted-foreground">
            Questions about these terms? Message us on Instagram{" "}
            <a href="https://instagram.com/userealtalk" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
              @userealtalk
            </a>.
          </p>
        </section>

      </div>
    </div>
  );
}
