/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyAdminRouteImport } from './routes/safety-admin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdviceAdminRouteImport } from './routes/advice-admin'
import { Route as AdviceRouteImport } from './routes/advice'
import { Route as AccountDataRouteImport } from './routes/account-data'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyAdminRoute = SafetyAdminRouteImport.update({
  id: '/safety-admin',
  path: '/safety-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceAdminRoute = AdviceAdminRouteImport.update({
  id: '/advice-admin',
  path: '/advice-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceRoute = AdviceRouteImport.update({
  id: '/advice',
  path: '/advice',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDataRoute = AccountDataRouteImport.update({
  id: '/account-data',
  path: '/account-data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-data': typeof AccountDataRoute
  '/advice': typeof AdviceRoute
  '/advice-admin': typeof AdviceAdminRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety-admin': typeof SafetyAdminRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-data': typeof AccountDataRoute
  '/advice': typeof AdviceRoute
  '/advice-admin': typeof AdviceAdminRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety-admin': typeof SafetyAdminRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-data': typeof AccountDataRoute
  '/advice': typeof AdviceRoute
  '/advice-admin': typeof AdviceAdminRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety-admin': typeof SafetyAdminRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-data'
    | '/advice'
    | '/advice-admin'
    | '/auth'
    | '/journal'
    | '/privacy'
    | '/profile'
    | '/recover'
    | '/reset-password'
    | '/safety-admin'
    | '/settings'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-data'
    | '/advice'
    | '/advice-admin'
    | '/auth'
    | '/journal'
    | '/privacy'
    | '/profile'
    | '/recover'
    | '/reset-password'
    | '/safety-admin'
    | '/settings'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/account-data'
    | '/advice'
    | '/advice-admin'
    | '/auth'
    | '/journal'
    | '/privacy'
    | '/profile'
    | '/recover'
    | '/reset-password'
    | '/safety-admin'
    | '/settings'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDataRoute: typeof AccountDataRoute
  AdviceRoute: typeof AdviceRoute
  AdviceAdminRoute: typeof AdviceAdminRoute
  AuthRoute: typeof AuthRoute
  JournalRoute: typeof JournalRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RecoverRoute: typeof RecoverRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyAdminRoute: typeof SafetyAdminRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-admin': {
      id: '/safety-admin'
      path: '/safety-admin'
      fullPath: '/safety-admin'
      preLoaderRoute: typeof SafetyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice-admin': {
      id: '/advice-admin'
      path: '/advice-admin'
      fullPath: '/advice-admin'
      preLoaderRoute: typeof AdviceAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice': {
      id: '/advice'
      path: '/advice'
      fullPath: '/advice'
      preLoaderRoute: typeof AdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-data': {
      id: '/account-data'
      path: '/account-data'
      fullPath: '/account-data'
      preLoaderRoute: typeof AccountDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDataRoute: AccountDataRoute,
  AdviceRoute: AdviceRoute,
  AdviceAdminRoute: AdviceAdminRoute,
  AuthRoute: AuthRoute,
  JournalRoute: JournalRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RecoverRoute: RecoverRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyAdminRoute: SafetyAdminRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
